name: main_practice
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.3
  intl: ^0.18.0
  watcher: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.5.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  arb_dir: lib/localization/l10n
  output_dir: lib/localization/l10n/generated

scripts: dart run merge_and_generate.dart
