// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9F0Zw2QxRTbKmpEBuEIwJH90UyJtsMSM',
    appId: '1:884224648489:web:462ea1bc9006e6940ec338',
    messagingSenderId: '884224648489',
    projectId: 'main-test-706f8',
    authDomain: 'main-test-706f8.firebaseapp.com',
    storageBucket: 'main-test-706f8.appspot.com',
    measurementId: 'G-P5B2K7SJLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC17DBycMW__HoSSA8sbzzRrEC1nITQ71g',
    appId: '1:884224648489:android:88841eb30293d4e70ec338',
    messagingSenderId: '884224648489',
    projectId: 'main-test-706f8',
    storageBucket: 'main-test-706f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSgSeKqyIa0RB8DxRscOm-mPfW7PooKy4',
    appId: '1:884224648489:ios:fc38c1ac129799350ec338',
    messagingSenderId: '884224648489',
    projectId: 'main-test-706f8',
    storageBucket: 'main-test-706f8.appspot.com',
    iosBundleId: 'com.example.mainPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSgSeKqyIa0RB8DxRscOm-mPfW7PooKy4',
    appId: '1:884224648489:ios:fc38c1ac129799350ec338',
    messagingSenderId: '884224648489',
    projectId: 'main-test-706f8',
    storageBucket: 'main-test-706f8.appspot.com',
    iosBundleId: 'com.example.mainPractice',
  );
}
