// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrxUMykVmkzZZ-WI9YyqijCJfYBroivAk',
    appId: '1:233383750102:web:53f4b23fd1d52caf7c1c77',
    messagingSenderId: '233383750102',
    projectId: 'apptest-6e253',
    authDomain: 'apptest-6e253.firebaseapp.com',
    storageBucket: 'apptest-6e253.appspot.com',
    measurementId: 'G-70BCWPD2TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4fma5VcozpXm2aQ3dUcoqSYG31MD1qu4',
    appId: '1:233383750102:android:3e4dd469abfa66a27c1c77',
    messagingSenderId: '233383750102',
    projectId: 'apptest-6e253',
    storageBucket: 'apptest-6e253.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGFeVtBZevbHh8WHHPkkf8GvCLOorJy3k',
    appId: '1:233383750102:ios:7e8f384dba20ce047c1c77',
    messagingSenderId: '233383750102',
    projectId: 'apptest-6e253',
    storageBucket: 'apptest-6e253.appspot.com',
    androidClientId: '233383750102-dic344tm7afkjo2n7dt9dm7gdcbrf03l.apps.googleusercontent.com',
    iosClientId: '233383750102-v6g602mthte1e2lqj7kudutjis5db3hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGFeVtBZevbHh8WHHPkkf8GvCLOorJy3k',
    appId: '1:233383750102:ios:7e8f384dba20ce047c1c77',
    messagingSenderId: '233383750102',
    projectId: 'apptest-6e253',
    storageBucket: 'apptest-6e253.appspot.com',
    androidClientId: '233383750102-dic344tm7afkjo2n7dt9dm7gdcbrf03l.apps.googleusercontent.com',
    iosClientId: '233383750102-v6g602mthte1e2lqj7kudutjis5db3hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainPractice',
  );
}
